import { Serie } from './Serie.js';
export const series = [
    new Serie(1, "Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer", "https://www.amc.com/shows/breaking-bad", "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/ec7e4abe-8847-4e05-a39a-26790d0cc2c1/d5628z3-4c1941a4-1f8a-4c3a-afc1-f1e2d83b68ef.png/v1/fill/w_851,h_314,q_80,strp/breaking_bad_fb_banner_by_cartoonperson_d5628z3-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MzE0IiwicGF0aCI6IlwvZlwvZWM3ZTRhYmUtODg0Ny00ZTA1LWEzOWEtMjY3OTBkMGNjMmMxXC9kNTYyOHozLTRjMTk0MWE0LTFmOGEtNGMzYS1hZmMxLWYxZTJkODNiNjhlZi5wbmciLCJ3aWR0aCI6Ijw9ODUxIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.LAutnTD0eoAxNdb_5zivFtYWkopE7__Wg5unVWQfMfQ"),
    new Serie(2, "Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary", "https://www.netflix.com/co/title/70242311", "https://ntvb.tmsimg.com/assets/p13812572_b_h10_aa.jpg?w=1280&h=720"),
    new Serie(3, "Game of Thrones", "HBO", 7, "American fantasy drama", "https://www.hbo.com/game-of-thrones", "https://scontent.fbog14-1.fna.fbcdn.net/v/t39.30808-6/453621523_1047509543402893_1578374590997114121_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=cc71e4&_nc_ohc=ZKDN3ZLE698Q7kNvgHhIY35&_nc_zt=23&_nc_ht=scontent.fbog14-1.fna&_nc_gid=AE9cuvn_lalkeVo1z2CE94m&oh=00_AYAaKo-YW6kXJzhdbvBI7mpRU_2J_-S5hAYP2m3c6uP5iw&oe=6718F3A1"),
    new Serie(4, "The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists—geniuses in the laboratory but socially challenged everywhere else. Enter beautiful, street-smart neighbor Penny, who aims to teach them a thing or two about life. Despite their on-again, off-again relationship in the past, Leonard and Penny have finally gotten married. Even Sheldon has found a female companion, entering into a relationship agreement with neurobiologist Amy Farrah Fowler, and he recently took their relationship to the next level by marrying her after a long courtship. In their free time, Leonard and Sheldon enjoy fantasy role-playing games with their ever-expanding universe of friends, including fellow scientists Koothrappali, Wolowitz, and Wolowitz’s adorable microbiologist wife, Bernadette, who is adjusting to life with their two children.", "https://www.cbs.com/shows/big_bang_theory/about/", "https://static.posters.cz/image/1300/posters/the-big-bang-theory-cast-i22637.jpg"),
    new Serie(5, "Sherlock", "BBC", 4, "Sherlock depicts consulting detective Sherlock Holmes (Benedict Cumberbatch) solving various mysteries in modern-day London. Holmes is assisted by his flatmate and friend, Dr John Watson (Martin Freeman), who has returned from military service in Afghanistan with the Royal Army Medical Corps", "https://www.bbc.co.uk/programmes/b018ttws", "https://mir-s3-cdn-cf.behance.net/project_modules/fs/e6fd3532032273.566b40caa5ef7.jpg"),
    new Serie(6, "A Very English Scandal", "BBC", 2, "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries based on John Preston's book of the same name.", "https://www.bbc.co.uk/programmes/p065smy4", "https://themarckoguy.wordpress.com/wp-content/uploads/2018/12/English_Scandal.jpg"),
];
